
package cz.toce.learn.javaee.ws.simplest.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleWebServiceImpl", targetNamespace = "http://api.simplest.ws.javaee.learn.toce.cz", wsdlLocation = "http://localhost:8080/ws/SimpleWebService?wsdl")
public class SimpleWebServiceImpl
    extends Service
{

    private final static URL SIMPLEWEBSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException SIMPLEWEBSERVICEIMPL_EXCEPTION;
    private final static QName SIMPLEWEBSERVICEIMPL_QNAME = new QName("http://api.simplest.ws.javaee.learn.toce.cz", "SimpleWebServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/SimpleWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEWEBSERVICEIMPL_WSDL_LOCATION = url;
        SIMPLEWEBSERVICEIMPL_EXCEPTION = e;
    }

    public SimpleWebServiceImpl() {
        super(__getWsdlLocation(), SIMPLEWEBSERVICEIMPL_QNAME);
    }

    public SimpleWebServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEWEBSERVICEIMPL_QNAME, features);
    }

    public SimpleWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEWEBSERVICEIMPL_QNAME);
    }

    public SimpleWebServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEWEBSERVICEIMPL_QNAME, features);
    }

    public SimpleWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleWebServicePortType
     */
    @WebEndpoint(name = "SimpleWebServiceSoap11Http")
    public SimpleWebServicePortType getSimpleWebServiceSoap11Http() {
        return super.getPort(new QName("http://api.simplest.ws.javaee.learn.toce.cz", "SimpleWebServiceSoap11Http"), SimpleWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleWebServicePortType
     */
    @WebEndpoint(name = "SimpleWebServiceSoap11Http")
    public SimpleWebServicePortType getSimpleWebServiceSoap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.simplest.ws.javaee.learn.toce.cz", "SimpleWebServiceSoap11Http"), SimpleWebServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEWEBSERVICEIMPL_EXCEPTION!= null) {
            throw SIMPLEWEBSERVICEIMPL_EXCEPTION;
        }
        return SIMPLEWEBSERVICEIMPL_WSDL_LOCATION;
    }

}
