
package cz.toce.learn.javaee.jaxws.simplest.fault.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InternalErrorException", targetNamespace = "http://api.fault.simplest.jaxws.javaee.learn.toce.cz")
public class InternalErrorExceptionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InternalErrorException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InternalErrorExceptionFault(String message, InternalErrorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InternalErrorExceptionFault(String message, InternalErrorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cz.toce.learn.javaee.jaxws.simplest.fault.api.InternalErrorException
     */
    public InternalErrorException getFaultInfo() {
        return faultInfo;
    }

}
