
package cz.toce.learn.javaee.jaxws.simplest.fault.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleWebServiceFaultPortType", targetNamespace = "http://api.fault.simplest.jaxws.javaee.learn.toce.cz")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleWebServiceFaultPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns cz.toce.learn.javaee.jaxws.simplest.fault.api.HelloResponse
     * @throws InternalErrorExceptionFault
     */
    @WebMethod
    @WebResult(name = "HelloResponse", targetNamespace = "http://api.fault.simplest.jaxws.javaee.learn.toce.cz", partName = "parameters")
    public HelloResponse helloMessage(
        @WebParam(name = "HelloRequest", targetNamespace = "http://api.fault.simplest.jaxws.javaee.learn.toce.cz", partName = "parameters")
        HelloRequest parameters)
        throws InternalErrorExceptionFault
    ;

}
