
package cz.toce.learn.javaee.ws.simplest.client.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimplestWebServiceImplService", targetNamespace = "http://simplest.ws.javaee.learn.toce.cz/client/api", wsdlLocation = "http://localhost:8080/ws/SimplestWebService?wsdl")
public class SimplestWebServiceImplService
    extends Service
{

    private final static URL SIMPLESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLESTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SIMPLESTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://simplest.ws.javaee.learn.toce.cz/client/api", "SimplestWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/SimplestWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SIMPLESTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SimplestWebServiceImplService() {
        super(__getWsdlLocation(), SIMPLESTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public SimplestWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLESTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimplestWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLESTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public SimplestWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLESTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimplestWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimplestWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimplestWebService
     */
    @WebEndpoint(name = "SimplestWebServicePort")
    public SimplestWebService getSimplestWebServicePort() {
        return super.getPort(new QName("http://simplest.ws.javaee.learn.toce.cz/client/api", "SimplestWebServicePort"), SimplestWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimplestWebService
     */
    @WebEndpoint(name = "SimplestWebServicePort")
    public SimplestWebService getSimplestWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://simplest.ws.javaee.learn.toce.cz/client/api", "SimplestWebServicePort"), SimplestWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLESTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SIMPLESTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SIMPLESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
