<?xml version="1.0" encoding="UTF-8"?>
<definitions name="HelloService" targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl">
 
   <message name="SayHelloRequest">
      <part name="firstName" type="xsd:string"/>
   </message>
	
   <message name="SayHelloResponse">
      <part name="greeting" type="xsd:string"/>
   </message>

   <portType name="HelloPortType">
      <operation name="sayHello">
         <input name="in1" message="tns:SayHelloRequest"/>
         <output name="out1" message="tns:SayHelloResponse"/>
      </operation>
   </portType>

   <binding name="HelloBinding" type="tns:HelloPortType">        
       <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="sayHello">
           <soap12:operation style="document" soapAction="sayHello" soapActionRequired="false"/>
           <input name="in1">
               <soap12:body use="literal"/>
           </input>
           <output name="out1">
               <soap12:body use="literal"/>
           </output>
      </operation>
   </binding>

   <service name="HelloSService">
      <documentation>WSDL File for HelloService</documentation>
      <port binding="tns:HelloBinding" name="Hello_Port">
         <soap12:address
            location="http://localhost:8080/SayHello/"></soap12:address>
      </port>
   </service>
</definitions>