
package cz.toce.learn.javaee.ws.simplest.client.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimplestWebService", targetNamespace = "http://simplest.ws.javaee.learn.toce.cz/client/api")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimplestWebService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://simplest.ws.javaee.learn.toce.cz/client/api", className = "cz.toce.learn.javaee.ws.simplest.client.api.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://simplest.ws.javaee.learn.toce.cz/client/api", className = "cz.toce.learn.javaee.ws.simplest.client.api.HelloResponse")
    @Action(input = "http://simplest.ws.javaee.learn.toce.cz/client/api/SimplestWebService/helloRequest", output = "http://simplest.ws.javaee.learn.toce.cz/client/api/SimplestWebService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
